# Generated by Django 6.0 on 2025-12-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='headshot',
            field=models.ImageField(null=True, upload_to='author_headshots'),
        ),
    ]
